part_system_destroy(part_sys);
part_type_destroy(part_type_explode);
part_type_destroy(part_type_explode_smoke);
part_type_destroy(part_type_explode_small);
part_type_destroy(part_type_spark);
part_type_destroy(part_type_missile_exhaust);
part_type_destroy(part_type_hit_char);
part_type_destroy(part_type_jet);
part_type_destroy(part_type_smoke);